### ISSUE TITLE
log_reader index -4

### ISSUE THREAD

**Issue by PandeoF1** [PandeoF1/42-taskmaster#70]
```yml
  - name: echo OUIII
    cmd: "echo OUIII"
    numprocs: 8
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 0
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/echo.stdout
    stderr: /tmp/echo.stderr
    user: test
```

│   Press 'q' to go back. - (↑•↓•←•→ to navigate) -4
