### ISSUE TITLE
Services - Start function avec autostart

### ISSUE THREAD

**Issue by PandeoF1** [PandeoF1/42-taskmaster#71]
```yml
  - name: echo OUIII
    cmd: "echo OUIII"
    numprocs: 8
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 0
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/echo.stdout
    stderr: /tmp/echo.stderr
    user: test
```

At the start there is 8 process but when you press 's' it start only 4 (or random number of process)
